# Repair the whole reactor, apply the patch to the project, then build it again.
invoker.goals.1 = compile ${project.groupId}:${project.artifactId}:${project.version}:repair
invoker.goals.2 = ${project.groupId}:${project.artifactId}:${project.version}:apply
invoker.goals.3 = compile
