package org.arodnap.engine.stages;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.TreeSet;
import org.arodnap.engine.files.FilePaths;
import org.arodnap.engine.json.Json;
import org.arodnap.engine.patch.Lines;
import org.arodnap.engine.patch.PatchApplier;
import org.arodnap.engine.patch.UnifiedDiff;
import org.arodnap.engine.pipeline.PatchLog;
import org.arodnap.engine.pipeline.Workspace;
import org.arodnap.model.StageResult;

/**
 * The patch bundle: one patch that turns the original project into the repaired workspace, over
 * exact bytes. It is only reported once applying it to a clean copy of the original files
 * reproduces the workspace contents exactly.
 */
public final class BundleStage implements Stage {
    public static final String NAME = "bundle";
    public static final String PATCH_FILE = "arodnap.patch";

    @Override
    public String name() {
        return NAME;
    }

    @Override
    public StageResult run(StageContext context) throws StageException {
        List<String> candidates = new ArrayList<>();
        context.previous().forEach(result -> candidates.addAll(result.changedFiles()));
        Path workspaceRoot = context.workspaceRoot();
        try {
            for (String line : Files.readAllLines(context.analysis().sourceFiles(), StandardCharsets.UTF_8)) {
                if (!line.isBlank()) {
                    candidates.add(FilePaths.relativeTo(Path.of(line.strip()), workspaceRoot).orElseThrow(
                            () -> new StageException("Source file outside the workspace: " + line.strip())));
                }
            }
            return bundle(context.run().workspace().repoRoot(), workspaceRoot, candidates, context.stageDirectory(NAME));
        } catch (IOException e) {
            throw new StageException("The bundle stage could not write its files: " + e.getMessage(), e);
        }
    }

    /** Diffs {@code candidates} (repository-relative) between the project and the workspace, and verifies the patch. */
    public static StageResult bundle(Path repoRoot, Path workspaceRoot, List<String> candidates, Path directory)
            throws IOException, StageException {
        Files.createDirectories(directory);
        Path log = directory.resolve("stage.log");
        Path patch = directory.resolve(PATCH_FILE);
        Path manifest = directory.resolve("patch_manifest.json");
        StageLog.reset(log);

        List<String> changed = new ArrayList<>();
        int notInRepository = 0;
        StringBuilder diffs = new StringBuilder();
        for (String relative : new TreeSet<>(candidates)) {
            Path original = repoRoot.resolve(relative);
            Path current = workspaceRoot.resolve(relative);
            if (!Files.isRegularFile(current)) {
                throw new StageException("Workspace file disappeared during repair: " + relative);
            }
            if (!Files.isRegularFile(original)) {
                // Generated by the build (e.g. annotation processor output): analyzed, never patched.
                notInRepository++;
                continue;
            }
            if (Arrays.equals(Files.readAllBytes(original), Files.readAllBytes(current))) {
                continue;
            }
            diffs.append(UnifiedDiff.create(relative, Lines.read(original), Lines.read(current)));
            changed.add(relative);
        }
        List<String> generatedNote = notInRepository > 0
                ? List.of("Left out " + notInRepository + " generated file(s) that are not in the repository.") : List.of();

        Map<String, String> artifacts = new LinkedHashMap<>();
        artifacts.put("log", log.toString());
        if (changed.isEmpty()) {
            Files.deleteIfExists(patch);
            writeManifest(manifest, List.of());
            artifacts.put("patch_manifest", manifest.toString());
            List<String> notes = new ArrayList<>(List.of("Repair produced no source changes."));
            notes.addAll(generatedNote);
            return StageLog.writeResult(directory, new StageResult(NAME, false, List.of(), false, artifacts, notes, true));
        }

        Lines.write(patch, diffs.toString());
        verify(repoRoot, workspaceRoot, changed, patch, log);
        Map<String, String> preimages = new LinkedHashMap<>();
        for (String relative : changed) {
            preimages.put(relative, RlPatcherStage.sha256(Files.readAllBytes(repoRoot.resolve(relative))));
        }
        Map<String, Object> entry = new LinkedHashMap<>();
        entry.put("patch_file", patch.toString());
        entry.put("stage", NAME);
        entry.put("strip_level", 0);
        entry.put("target_root", ".");
        entry.put("changed_files", changed);
        entry.put("preimage_hashes", preimages);
        writeManifest(manifest, List.of(entry));
        artifacts.put("patch", patch.toString());
        artifacts.put("patch_manifest", manifest.toString());
        List<String> notes = new ArrayList<>(List.of("Bundled changes to " + changed.size()
                + " file(s) and verified them against the original repository."));
        notes.addAll(generatedNote);
        return StageLog.writeResult(directory, new StageResult(NAME, false, changed, false, artifacts, notes, true));
    }

    private static void verify(Path repoRoot, Path workspaceRoot, List<String> changed, Path patch, Path log)
            throws IOException, StageException {
        Path clean = Files.createTempDirectory("arodnap-bundle-check-");
        try {
            for (String relative : changed) {
                Path target = clean.resolve(relative);
                Files.createDirectories(target.getParent());
                Files.copy(repoRoot.resolve(relative), target);
            }
            PatchApplier.Outcome outcome = PatchLog.apply(clean, patch, PatchApplier.Options.EXACT, log, "verify_bundle");
            if (!outcome.ok()) {
                throw new StageException("Bundle does not apply to the original repository. See log: " + log);
            }
            for (String relative : changed) {
                if (!Arrays.equals(Files.readAllBytes(clean.resolve(relative)), Files.readAllBytes(workspaceRoot.resolve(relative)))) {
                    throw new StageException("Bundle does not reproduce the repaired contents of " + relative + ".");
                }
            }
        } finally {
            Workspace.deleteTree(clean);
        }
    }

    private static void writeManifest(Path manifest, List<Map<String, Object>> patches) throws IOException {
        Map<String, Object> json = new LinkedHashMap<>();
        json.put("stage", NAME);
        json.put("patches", patches);
        Json.writeFile(manifest, json, true);
    }
}
